apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-ettersending
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '25M'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '120'
    texas.nais.io/enabled: 'true'
spec:
  replicas:
    min: 2
    max: 2
  port: 9000
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - 'https://www.nav.no/familie/alene-med-barn/ettersending'
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /familie/alene-med-barn/ettersending/**/*.css
      level: Level4
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-soknad-api
        - application: familie-dokument
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: nav.no
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 256Mi
      cpu: 100m
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: ENV
      value: prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
