apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-ettersending
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 9000
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - "https://www.nav.no/familie/alene-med-barn/ettersending"
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: Level4
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-soknad-api
        - application: familie-ef-dokument
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  env:
    - name: APP_VERSION
      value: "{{version}}"
    - name: ENV
      value: prod
    - name: BASE_PATH
      value: "{{base_path}}"