apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-ettersending
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 0
    max: 0
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - "https://ensligmorellerfar.dev.nav.no/familie/alene-med-barn/ettersending"
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  env:
    - name: APP_VERSION
      value: "{{version}}"
    {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
    {{/each}}