export enum StønadType {
  OVERGANGSSTØNAD = 'Overgangsstønad',
  BARNETILSYN = 'Barnetilsyn',
  SKOLEPENGER = 'Skolepenger',
}

export enum DokumentType {
  DOKUMENTASJON_IKKE_VILLIG_TIL_ARBEID = 'Dokumentasjon som beskriver grunnen til at du ikke kan ta ethvert arbeid',
  DOKUMENTAJSON_SYK = 'Dokumentasjon på at du er syk',
  DOKUMENTAJSON_OM_VIRKSOMHETEN_DU_ETABLERER = 'Næringsfaglig vurdering av virksomheten du etablerer',
  DOKUMENTASJON_UTFGIFTER_UTDANNING = 'Utgifter til skolepenger',
  DOKUMENTASJON_ARBEIDSKONTRAKT = 'Arbeidskontrakt som viser at du har fått tilbud om arbeid.',
  DOKUMENTASJON_LÆRLING = 'Lærlingkontrakt',
  TERMINBEKREFTELSE = 'Terminbekreftelse',
  FAKTURA_FRA_BARNEPASSORDNING = 'Faktura fra barnepassordningen for perioden du søker om nå',
  AVTALE_MED_BARNEPASSER = 'Avtalen du har med barnepasseren',
  DOKUMENTASJON_TRENGER_MER_PASS_ENN_JEVNALDREDE = 'Dokumentasjon på at barnet ditt har behov for vesentlig mer pass enn det som er vanlig for jevnaldrende',
  DOKUMENTASJON_UTENOM_VANLIG_ARBEIDSTID = 'Dokumentasjon på at du jobber turnus eller skift, og jobber på tider utenom vanlig arbeidstid',
  DOKUMENTASJON_MYE_BORTE_PGA_JOBB = 'Dokumentasjon på at du må være borte fra hjemmet i lengre perioder på grunn av jobb',
  DOKUMENTASJON_BOR_PÅ_ULIKE_ADDRESSER = 'Dokumentasjon på at du og tidligere samboer bor på ulike adresser',
  DOKUMENTAJSON_BARN_BOR_HOS_DEG = 'Dokumentasjon på at barn bor hos deg',
  AVTALE_OM_DELT_BOSTED = 'Avtale om delt bosted',
  SAMVÆRSAVTALE_MED_KONKRETE_TIDSPUNKTER = 'Samværsavtale med konktrete tidspunkter',
  SAMVÆRSAVTALE_UTEN_KONKRETE_TIDSPUNKTER = 'Samværsavtale uten konkrete tidspunkter',
  DOKUMENTASJON_SYKDOM = 'Dokumentasjon på at du er syk',
  DOKUMENTASJON_SYKT_BARN = 'Dokumentasjon på barnets sykdom',
  DOKUMENTASJON_BARNEPASS_MANGEL = 'Dokumentasjon på at du mangler barnepass ',
  DOKUMENTASJON_BARNETILSYN_BEHOV = 'Dokumentasjon på barnets tilsynsbehov',
  ARBEIDSFORHOLD_OG_OPPSIGELSESÅRSAK = 'Dokumentasjon på arbeidsforholdet og årsaken til at du sluttet',
  ARBEIDSFORHOLD_OG_REDUSERT_ARBEIDSTID = 'Dokumentasjon på arbeidsforholdet og årsaken til at du reduserte arbeidstiden',
  ERKÆRING_SAMMLIVSBRUDD = 'Bekreftelse på samlivsbrudd med den andre forelderen',
  DOKUMENTASJON_INNGÅTT_EKTESKAP = 'Dokumentasjon på inngått ekteskap',
  DOKUMENTASJON_UFORMELT_SEPARERT_ELLER_SKILT = 'Dokumentasjon på separasjon eller skilsmisse',
  BEKREFTELSE_SEPRASJON_SØKNAD = 'Dokumentasjon på separasjon eller skilsmisse',
}
